# Generated by Django 4.0.dev20210401123330 on 2022-04-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_record_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.FileField(blank=True, upload_to='my_picture'),
        ),
    ]
